### ISSUE TITLE
Not getting the proper formatted verse

### ISSUE THREAD

**Issue by apitlekays** [quran/api-js#3]
**Environment:** 

- React Native
- @quranjs/api : "^1.5.0"
- UI framework: UI Kitten

**Problem:**
I have queried verse by chapter id `quran.v4.verses.findByChapter(1,{language:'ms', words: true})` and stored it in AsyncStorage.
I then display the list of verses via FlatList(React Native) or List(UI Kitten). This is where the problem occurs.

I believe that I got the correct array of objects for the queried id.
This is what I got:
```
[
    {"hizbNumber": 1, 
    "id": 1, 
    "juzNumber": 1, 
    "manzilNumber": 1, 
    "pageNumber": 1, 
    "rubElHizbNumber": 1, 
    "rukuNumber": 1, 
    "sajdahNumber": null, 
    "verseKey": "1:1", 
    "verseNumber": 1, 
    "words": [[Object], [Object], [Object], [Object], [Object]]
}, {
    "hizbNumber": 1, 
    "id": 2, 
    "juzNumber": 1, 
    "manzilNumber": 1, 
    "pageNumber": 1, 
    "rubElHizbNumber": 1, 
    "rukuNumber": 1, 
    "sajdahNumber": null, 
    "verseKey": "1:2", 
    "verseNumber": 2, 
    "words": [[Object], [Object], [Object], [Object], [Object]]
}, { ... } //concatenated for breivity
```
so in the `renderItem` of the FlatList, I use `.map` function to get the list of texts from the `words`, but they are not the actual verses of the Surah. 

The renderItem :
```
const VerseItem = ({item, index}) => {
        return(
            <View style={{ backgroundColor:'blue', flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', padding: 20}}>
                {
                    item.words.map((word) => {
                        return (
                            <Text style={{ color: '#fff' }} key={ word.id }>{word.text}</Text>
                        )
                    })
                }
            </View>
        )
    }
```

**Result:**
<img width="432" alt="Screenshot 2022-10-18 at 11 45 40 PM" src="https://user-images.githubusercontent.com/3820817/196479371-1be9ef47-1fb8-495d-9f5b-7b886b0e84d4.png">

**Comment by ahmedriad1** [comment]
Hey Hafiz, 

Sorry for the late reply. `Word.text` is the QFC (a special Quran font) version. If you want the normal Arabic text you can use `Word.textUthmani`
